osx_image: xcode10.1  # define OS X image which will be mounted

dist: trusty  # use Ubuntu Trusty for Linux operation system

# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: false

language: node_js
node_js: "10"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN_GPG=no

os:
  - linux
  - osx
  - windows

cache:
  yarn: true
  timeout: 1200
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install rpm; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm install --global --production windows-build-tools --vs2015; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell -ExecutionPolicy ByPass -File db/scripts/travis_download_pg.ps1; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./resetvars.bat; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PATH=$PATH:`pwd`/PostgreSQL/pgsql/bin; fi
  - travis_wait yarn install --network-timeout 1000000

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release --mac; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then yarn release --win; fi

before_cache:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
